# Generated by Django 4.0.6 on 2022-08-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_url', models.URLField()),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('business_address', models.CharField(blank=True, max_length=30, null=True)),
                ('can_create_acct', models.BooleanField(blank=True, null=True)),
                ('can_buy_goods', models.BooleanField(blank=True, null=True)),
                ('use_feedback', models.BooleanField(blank=True, null=True)),
                ('contact_info', models.EmailField(blank=True, max_length=254, null=True)),
                ('age_limit', models.IntegerField(blank=True, null=True)),
                ('additional_text', models.TextField(blank=True, null=True)),
                ('permanent', models.BooleanField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('last_edit', models.DateTimeField()),
            ],
            options={
                'ordering': ['last_edit'],
            },
        ),
    ]
